# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: ruff (linter)
        args: [--fix]
      - id: ruff-format
        name: ruff (formatter)
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.11.2
    hooks:
      - id: snakefmt
  - repo: https://github.com/fsfe/reuse-tool
    rev: v4.0.3
    hooks:
      - id: reuse
