# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

version = 1
SPDX-PackageName = "food-opt"
SPDX-PackageSupplier = "Koen van Greevenbroek"
SPDX-PackageDownloadLocation = "https://github.com/koen-vg/food-opt"

[[annotations]]
path = [
    "data/manually_downloaded/GDD-dietary-intake/**",
    "data/manually_downloaded/GDD-dietary-intake/**.csv",
    "data/manually_downloaded/GDD-dietary-intake/**.xlsx"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Tufts University"
SPDX-License-Identifier = "LicenseRef-GDD-NonCommercial"

[[annotations]]
path = [
    "data/manually_downloaded/IHME-GBD_2021-dealth-rates.csv",
    "data/manually_downloaded/IHME_GBD_2019_RELATIVE_RISKS_Y2020M10D15.XLSX"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Institute for Health Metrics and Evaluation (IHME)"
SPDX-License-Identifier = "LicenseRef-IHME-NonCommercial"

[[annotations]]
path = "data/M49-codes.csv"
precedence = "override"
SPDX-FileCopyrightText = "2025 United Nations Statistics Division"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "data/**.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Koen van Greevenbroek"
SPDX-License-Identifier = "PDDL-1.0"

[[annotations]]
path = "docs/_static/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Koen van Greevenbroek"
SPDX-License-Identifier = "CC-BY-4.0"
