# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

name: "validation"
scenario_defs: "config/validation_scenarios.yaml"

planning_horizon: 2020

validation:
  use_actual_yields: true
  use_actual_production: true
  enforce_gdd_baseline: true
  slack_marginal_cost: 10
  harvest_area_source: "gaez" # "cropgrids"

land:
  regional_limit: 1.

macronutrients:
  cal:
    min: 2000

health:
  enabled: false

solving:
  io_api: "direct"
  solver: "highs"
  threads: 1
